management:
  endpoint:
    web:
      exposure:
        inculde: info, refresh, keepalive, health
logging:
  level:
    org.springframework.cloud.kubernetes: WARN

spring:
  application:
    name: minikube-sample
